### ISSUE TITLE
New alternative font Color and dialog colors

### ISSUE THREAD

**Issue by m1024x** [pingflood/GMenuNext#1]
Yeah, first issue! :-)

Here are some things I noticed with the 2018-05-06 release (PSNext, fontAlt white):

1) fontAltOutline (#00000000) is not loaded from skin config, default value is used and written to config.

2) Messagebox colors should be unified:
If we use a white color as fontAlt, the selector and dialogs look good (white text and icons on bottom, white text in dark grey preview area), but the shutdown/suspend dialogs become white on light grey as they use messageBoxBg as background. I think messageBoxBg was intended to be used with the normal font color. As it has buttons it's more similar to the bottom bar and should use that background color instead of the messageBoxBg color.

**Comment by pingflood** [comment]
1. Probably won't fix totally, because there's need for a workaround in case fontAlt and fontAltOutline are not defined in skin. There's need to set a default Alt color to not break a skin that was not updated yet. For now, it will check if the font have alpha == 0 and then will use regular font color. 

2. I don't think I understand your suggestion. For now, Alt colors are used in top/bottom/section bar and in messagebox dialogs. Do you think messageBoxBg and bottomBarBg should be the same color?

**Comment by m1024x** [comment]
2. Currently there are two different color combinations used for dialogs/popups/messageboxes. When we set the fontAlt color on PSNext to white the problem becomes visible:

- dialog top and bottom bar text, selector: **light on dark** (color fontAlt on topBarBg/bottomBarBg)
Here the white alt color is used on the darker top and bottom bar, so that we have a good contrast. In the file selector we have the same good contrast on the darker preview area. I think that's what fontAlt was intended for. In general the button icon color will match fontAlt most of the time to be visible on the bottom bar. And having a light list area and dark preview area (or the other way around) is essential for that emulation station look.

- 'Launching Yxz', link context menu: **dark on light** (color font on messageBoxBg)
These are text only popups without buttons that use the original font color.

- 'Suspend', 'Poweroff popup', 'Screenshot saved' and perhaps others: **light on light** (color fontAlt on messageBoxBg, almost unreadable)
In case of the poweroff popup we have buttons and should not only use fontAlt, but also the topBarBg or BottomBarBg colors. This would match the usage of fontAlt on top and bottom bars in dialogs (see first bullet).

To avoid that light text on light background problem, we should use bottomBarBg for the whole dialog or at least for the frame around the dialog including the buttons at the bottom. If we only use it for the outer frame the inner area should be 'font' on 'messageBoxBg' and the frame should be 'fontAlt' on 'bottomBarBg'. Not sure which variant looks better...

**Comment by pingflood** [comment]
Dialogs have it's own bg color (messageBoxBg). When I added fontAlt, the intended use is in dialogs/popups and top/section/bottom bars.. +/- the inverse logic of what you are suggesting (not to use bottomBarBg on messageBoxBg, but instead use fontAlt on BottomBar and MessageBox). ;)

This way, the skin designer can tweak bottom bar and message box bg (e.g., a slightly different tone on bars and dialogs, but all using the same dark/light tint).

Also, messageBoxBg came from legacy GMenu2X. Even though I agree with you, it could use the same bottomBarBg, I will not unify it to keep older skins compatibility.

The problem with 'Launching Yxz' is because it don't use a messagebox dialog, but a direct screen write. That's why it went unnoticed in this first fontAlt commit. I'll fix that.

In yesterday's commits I've added an option to change font color directly on write function. It will help to adjust this kind of glitches without too much workaround.

There may be more such dialogues not drawn by Message Box (e.g., shutdown, suspend..). I'll look for it and if you notice any other problem like this in next release, please report and I'll fix.

**Comment by pingflood** [comment]
Please test this version and check if you find any discrepancies with dialogs and fontAlt
[gmenu2x_fontAlt.zip](https://github.com/pingflood/GMenuNext/files/1983892/gmenu2x_fontAlt.zip)

**Comment by m1024x** [comment]
This version seems to fix the fontAlt issue. I updated my skins accordingly (messageBoxBg).

**Comment by pingflood** [comment]
Ok! Thanks for testing and reporting. I'll close this issue.

I have yet a small batch of internal changes to do and as soon as I finishes it, I'll pack a new release with your updated skin pack.
