### ISSUE TITLE
can't run apps

### ISSUE THREAD

**Issue by tackro** [pingflood/GMenuNext#4]
since last update I can't run any apps/games/emulators. it loads but always comes back to gmenu2x screen

**Comment by tackro** [comment]
suceed on execute commander only by add a new link

**Comment by pingflood** [comment]
Hi @tackro !

In first release there was a problem when running apps with overclock set. I updated the release few minutes after the issue was detected.

If you haven't tried yet, please download the release again and overwrite your previous gmenu2x binary.

I'll close this issue for now, but if the problem still occurs, please open it again with more details on what is happening.
